name: lgs_audiopedia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter 
  intl: ^0.17.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  audio_video_progress_bar: ^0.9.0
  animated_splash_screen: ^1.1.0
  audioplayers: ^0.20.1
  # device_preview: ^0.7.4
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0
  dotted_border: ^2.0.0+1
  flutter_custom_clippers: ^2.0.0
  wave_progress_bars: ^0.1.0
  provider: ^5.0.0-nullsafety.5
  share_plus: ^3.0.4
  flutter_downloader: ^1.7.1
  path_provider: ^2.0.6
  permission_handler: ^8.2.6
  image_picker: ^0.8.4+4
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  
#   flutter_launcher_icons: ^0.9.2

# flutter_icons:
#   image_path: "assets/lg_pashto.png"
#   image_path_android: "assets/exchange.png"
#   image_path_ios: "assets/exchange.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
#   adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#   adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/applogo.png"
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/sound_audio.mp3
    - assets/pushto_audios/
    - assets/urdo_audios/lg_urdo_audios/
    # - assets/covid_urdo_audios/
    # - assets/pushto_audios/pashto_covid_audios/
    - assets/pushto_audios/covid_pashto_audios/
    - assets/pushto_audios/lg_pashto_audios/

    - assets/urdo_audios/lg_urdo_audios/
    - assets/urdo_audios/urdo_covid_audios/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
